update:
	mvn install -DskipTests -Dmaven.test.skip=true  -Dmaven.javadoc.skip=true
	#cp target/pitest-0.34-RUBYALL.jar /home/rahul/.m2/repository/org/pitest/pitest/0.34-RUBYALL/pitest-0.34-RUBYALL.jar
	#java HashIt target/pitest-0.34-RUBYALL.jar > /home/rahul/.m2/repository/org/pitest/pitest/0.34-RUBYALL/pitest-0.34-RUBYALL.jar.sha1
